<a href="https://colab.research.google.com/github/yash-316/Movie-API-Fetch/blob/main/FetchingDataFromAPI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import requests

In [24]:
response  = requests.get('https://api.themoviedb.org/3/discover/movie?api_key=eb37da2277a38e747154b8986be0244f')

In [25]:
temp_df = pd.DataFrame(response.json()['results'])[['id','overview','release_date','popularity','vote_average','vote_count']]

In [26]:
temp_df

,id,overview,release_date,popularity,vote_average,vote_count
0,969681,Fighting crime full-time as Spider-Man in a wo...,2026-07-29,666.5009,7.861,2817
1,1423191,Medical courier Bryan unwittingly finds himsel...,2026-09-16,607.7799,7.330,289
2,1101383,After a mysterious cosmic event rips Oak Stree...,2026-08-12,528.4832,7.022,1390
3,1204680,After Acme products fail him one too many time...,2026-08-20,438.3449,7.500,476
4,1375646,Professor Se-jeong is thrust into a bloody nig...,2026-05-21,318.7187,8.082,850
5,1368337,"Odysseus, the legendary King of Ithaca, embark...",2026-07-15,355.3396,8.016,3849
6,1294189,A falsely accused war hero with nothing to los...,2026-10-29,277.1521,0.000,0
7,1482547,When her ground-breaking pharmaceutical discov...,2026-08-31,206.5334,7.600,12
8,1285366,"A romance about a man and a woman who, due to ...",2024-07-06,195.7847,5.688,8
9,1108427,"Teenage Moana answers the Ocean's call and, fo...",2026-07-08,194.5217,7.417,741
10,1288445,After witnessing his billionaire boss' murder ...,2026-08-19,239.8630,6.425,429
11,1440098,"Marfil, daughter of a powerful Spanish busines...",2026-09-09,160.0298,6.637,106
12,1084244,When Bonnie receives a Lilypad tablet as a gif...,2026-06-17,152.2425,8.400,2239
13,1386315,"Maia Marten, a brilliant London lawyer, has he...",2026-09-03,133.5525,6.747,547
14,1339713,"After breaking the mysterious ""One Wish Willow...",2026-05-13,142.2624,8.194,5666
15,1232569,Influenced by a sinister Cricket and created b...,2026-07-22,138.0530,6.590,105
16,1315772,"This is the rambunctious, ridiculous and total...",2026-06-24,124.9588,7.554,1156
17,1323244,A story about a woman from the International S...,2026-08-06,119.9367,6.712,170
18,1469930,While investigating their father’s death insid...,2026-05-13,114.4236,3.900,5
19,1408162,A celebrated Olympian shooter travels to Ameri...,2026-08-14,106.3914,7.300,28

In [27]:
df = pd.DataFrame()

In [31]:
for i in range(1, 429):
    response = requests.get(
        'https://api.themoviedb.org/3/discover/movie?api_key=eb37da2277a38e747154b8986be0244f&page={}'.format(i)
    )

    temp_df = pd.DataFrame(response.json()['results'])[
        ['id', 'overview', 'release_date', 'popularity', 'vote_average', 'vote_count']
    ]

    df = pd.concat([df, temp_df], ignore_index=True)

In [32]:
df

,id,overview,release_date,popularity,vote_average,vote_count
0,969681,Fighting crime full-time as Spider-Man in a wo...,2026-07-29,666.5009,7.861,2817
1,1423191,Medical courier Bryan unwittingly finds himsel...,2026-09-16,607.7799,7.330,289
2,1101383,After a mysterious cosmic event rips Oak Stree...,2026-08-12,528.4832,7.022,1390
3,1204680,After Acme products fail him one too many time...,2026-08-20,438.3449,7.500,476
4,1375646,Professor Se-jeong is thrust into a bloody nig...,2026-05-21,318.7187,8.082,850
...,...,...,...,...,...,...
8555,730047,"A man ahead of his time, Cyrano de Bergerac da...",2021-12-17,5.8556,6.326,336
8556,1285669,Four teenage slackers attempt a multi-million-...,2026-05-15,5.8552,7.200,23
8557,581859,Four African-American Vietnam veterans return ...,2020-06-12,5.8552,6.420,1200
8558,6280,A research scientist becomes the world's first...,1994-11-22,5.8552,5.197,1704
8559,9967,A group of Vietnam War veterans re-unite to re...,1983-12-16,5.8527,6.236,231

In [33]:
df.shape

(8560, 6)

In [34]:
df.to_csv('movies.csv')